### ISSUE TITLE
Head's up: Version reporting from 4.6.0 onwards

### ISSUE THREAD

**Issue by querkmachine** [Nooshu/fe-detection#2]
Hey Matt 👋 

As of the recently released 4.6.0, we now report what version of Frontend is in use directly in the code we release. We've done this for several reasons, including to help us track how fast new versions roll out, to help debug support requests, and because service teams are moving more towards customising how they use Frontend—be that through only importing and using certain components, or adding lots of bespoke code on top of it.

In JavaScript, we export the version as part of the global `GOVUKFrontend` object.

```js
window.GOVUKFrontend.version
// => "4.6.0"
```

We also include it within our CSS, in case a user has changed the JavaScript build pipeline for their project. In CSS, it looks like this:

```css
:root{
  --govuk-frontend-version: "4.6.0";
}
```

It can be grabbed by JS with this snippet: 

```js
getComputedStyle(document.documentElement).getPropertyValue("--govuk-frontend-version") 
// => '"4.6.0"' (note the two sets of quotes)
```

Might be useful to know, assuming this tool is still being maintained!

**Comment by Nooshu** [comment]
Thanks, @querkmachine! I've now deprecated this and linked to this issue from the README.md.

I didn't realise the version is exposed via JavaScript too! 😍
